### ISSUE TITLE
Error: Cannot find module 'dotenv'

### ISSUE THREAD

**Issue by xiaowenlong100** [certusone/wormhole#780]
How to solve the dotenv module no found question?
I try to execute 'yarn' under sdk/js directory and use the latest code.
------------------------------------------------------------------------
> wormhole@1.0.0 build
> truffle compile

Error: Cannot find module 'dotenv'
Require stack:
- /home/ubuntu/code/wormhole/ethereum/truffle-config.js
- /home/ubuntu/.nvm/versions/node/v16.13.0/lib/node_modules/truffle/node_modules/original-require/index.js
- /home/ubuntu/.nvm/versions/node/v16.13.0/lib/node_modules/truffle/build/cli.bundled.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/ubuntu/code/wormhole/ethereum/truffle-config.js:1:1)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at Object.require (node:internal/modules/cjs/helpers:102:18)
    at Function.load (/home/ubuntu/.nvm/versions/node/v16.13.0/lib/node_modules/truffle/build/webpack:/packages/config/dist/index.js:159:1)
    at Function.detect (/home/ubuntu/.nvm/versions/node/v16.13.0/lib/node_modules/truffle/build/webpack:/packages/config/dist/index.js:148:1)
    at Object.module.exports [as run] (/home/ubuntu/.nvm/versions/node/v16.13.0/lib/node_modules/truffle/build/webpack:/packages/core/lib/commands/compile/run.js:8:1)
    at Command.run (/home/ubuntu/.nvm/versions/node/v16.13.0/lib/node_modules/truffle/build/webpack:/packages/core/lib/command.js:189:1)
Truffle v5.4.30 (core: 5.4.30)
Node v16.13.0

**Comment by xiaowenlong100** [comment]
I have installed dotenv by `yarn add dotenv` and `npm install -g dotenv`
