### ISSUE TITLE
"Uncaught TypeError: Class extends value undefined is not a constructor or null" when integrate javascript sdk with my vite react project

### ISSUE THREAD

**Issue by Yammoe** [certusone/wormhole#985]
I'm working on ReactJS project using vite as bundler. Imported some function from Wormhold SDK and got this error:

browser.js:8 Uncaught TypeError: Class extends value undefined is not a constructor or null
    at browser.js:8:1
    at WebSocketClient.ts:129:38
    at node_modules/@terra-money/terra.js/dist/client/WebSocketClient.js (WebSocketClient.ts:248:1)
    at __require2 (chunk-DLOBKPOF.js?v=9824dde1:48:50)
    at node_modules/@terra-money/terra.js/dist/client/index.js (index.ts:10:1)
    at __require2 (chunk-DLOBKPOF.js?v=9824dde1:48:50)
    at node_modules/@terra-money/terra.js/dist/index.js (index.ts:3:1)
    at __require2 (chunk-DLOBKPOF.js?v=9824dde1:48:50)
    at node_modules/@certusone/wormhole-sdk/lib/cjs/token_bridge/attest.js (attest.js:41:18)
    at __require2 (chunk-DLOBKPOF.js?v=9824dde1:48:50)

Not sure which function cause this, but I think the reason might be relevant to commonjs or esm build. My vite.config.ts

import { defineConfig, loadEnv } from 'vite';
import react from '@vitejs/plugin-react';
import * as path from 'path';
import alias from '@rollup/plugin-alias';

// https://vitejs.dev/config/
export default ({ mode}) => {
  return defineConfig({
    plugins: [
      alias(),
      react(),
    ],
    resolve: {
      alias: {
        'src': path.resolve(__dirname, 'src'),
        crypto: 'crypto-js',
        fs: require.resolve('rollup-plugin-node-builtins'),
      }
    },
    server: {
      port: 3001,
    },
    define: {
      "global": {},
      "process.env.NODE_DEBUG": JSON.stringify(""),
    },
    build: {
      rollupOptions: {
        output: {
          manualChunks(id) {
            if (id.includes('react-custom-scrollbars-2')) return 'react-custom-scrollbars-2';
            if (id.includes('moment')) return 'moment';
            if (id.includes('lodash')) return 'lodash';
            if (id.includes('bignumber')) return 'bignumber.js';
            if (id.includes('axios')) return 'axios';
            if (id.includes('node_modules')) return 'vendor';
          }
        }
      }
    },
  })
};

I've been working around for weeks but no solution found.

**Comment by evan-gray** [comment]
> Try [this](https://medium.com/@ftaioli/using-node-js-builtin-modules-with-vite-6194737c2cd2)

Closing as it looks like these should work. Thanks @honeymaro
